/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hello_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     Hello
 * Method:    staticFn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hello_staticFn
  (JNIEnv *, jclass);

/*
 * Class:     Hello
 * Method:    passStr2cpp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Hello_passStr2cpp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Hello
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Hello_getStr
  (JNIEnv *, jobject);

/*
 * Class:     Hello
 * Method:    sumArr
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Hello_sumArr
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Hello
 * Method:    setArr
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Hello_setArr
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Hello
 * Method:    getStrArr
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Hello_getStrArr
  (JNIEnv *, jobject, jint);

/*
 * Class:     Hello
 * Method:    getInt2DArr
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Hello_getInt2DArr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Hello
 * Method:    register2native
 * Signature: (LHello;)V
 */
JNIEXPORT void JNICALL Java_Hello_register2native
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Hello
 * Method:    checkIsSameObj
 * Signature: (LHello;)Z
 */
JNIEXPORT jboolean JNICALL Java_Hello_checkIsSameObj
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Hello
 * Method:    testLocalRefUpperBound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hello_testLocalRefUpperBound
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
